train_input:
  func: 'deepimpression.data.v1.get_train_data_loader_cs'
  x: '/projects/bblg/mkrafcz2/deepimpression/X_train_ZTF_Sim_FullSliced_Padded_0pt2GP_hostPhotTrue_30Cut.npz'
  y: '/projects/bblg/mkrafcz2/deepimpression/y_train_ZTF_Sim_FullSliced_Padded_0pt2GP_hostPhotTrue_30Cut.npz'
  batch_size: 32
  shuffle: True

eval_input:
  func: 'deepimpression.data.v1.get_eval_data_loader_cs'
  x: '/projects/bblg/mkrafcz2/deepimpression/X_test_ZTF_Sim_FullSliced_Padded_0pt2GP_hostPhotTrue_30Cut.npz'
  y: '/projects/bblg/mkrafcz2/deepimpression/y_test_ZTF_Sim_FullSliced_Padded_0pt2GP_hostPhotTrue_30Cut.npz'
  batch_size: 32
  shuffle: False

model:
  func: 'deepimpression.models.t2model_v1.model.T2ModelFunc'
  input_dim: [12, 150]
  num_classes: 3
  embed_dim: 32
  ff_dim: 128
  num_filters: 32
  num_layers: 4
  num_heads: 2
  droprate: 0.28

optimizer:
    optimizer_type: "SGD"
    learning_rate: 0.001
    momentum: 0.0
    loss_scaling_factor: 1.0

runconfig:
  num_epochs: 200
